# Generated by Django 5.2.2 on 2025-06-17 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='api.facility'),
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('name', 'facility')},
        ),
    ]
