# Generated by Django 5.2.2 on 2025-06-17 12:40

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stockitem_facility_alter_stockitem_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adversedrugreaction',
            options={'ordering': ['-reaction_date'], 'verbose_name': 'Adverse Drug Reaction', 'verbose_name_plural': 'Adverse Drug Reactions'},
        ),
        migrations.AlterModelOptions(
            name='adverseeventfollowingimmunization',
            options={'ordering': ['-event_date'], 'verbose_name': 'Adverse Event Following Immunization', 'verbose_name_plural': 'Adverse Events Following Immunization'},
        ),
        migrations.AlterModelOptions(
            name='allergy',
            options={'verbose_name_plural': 'Allergies'},
        ),
        migrations.AlterModelOptions(
            name='inventoryhistory',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Inventory History', 'verbose_name_plural': 'Inventory History'},
        ),
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name_plural': 'Medical History'},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-order_date']},
        ),
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-change_date'], 'verbose_name': 'Order History', 'verbose_name_plural': 'Order History'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pastprocedure',
            options={'ordering': ['-procedure_date'], 'verbose_name': 'Past Procedure', 'verbose_name_plural': 'Past Procedures'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'ordering': ['-visit_date'], 'verbose_name': 'Patient Visit', 'verbose_name_plural': 'Patient Visits'},
        ),
        migrations.AlterModelOptions(
            name='paymenttransaction',
            options={'ordering': ['-transaction_date'], 'verbose_name': 'Payment Transaction', 'verbose_name_plural': 'Payment Transactions'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-prescription_date']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stockitem',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vitals',
            options={'verbose_name_plural': 'Vitals'},
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_price',
            new_name='price_at_order',
        ),
        migrations.RenameField(
            model_name='prescription',
            old_name='prescribed_date',
            new_name='prescription_date',
        ),
        migrations.RenameField(
            model_name='vitals',
            old_name='body_temperature',
            new_name='temperature',
        ),
        migrations.RemoveField(
            model_name='adverseeventfollowingimmunization',
            name='reaction_description',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='dosage_form',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='manufacturer',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='strength',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='expected_delivery_date',
        ),
        migrations.RemoveField(
            model_name='order',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='change_type',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='received_quantity',
        ),
        migrations.RemoveField(
            model_name='pastprocedure',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='pastprocedure',
            name='performing_physician',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_group',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_of_kin_contact',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='next_of_kin_name',
        ),
        migrations.RemoveField(
            model_name='patientvisit',
            name='reason_for_visit',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='amount_covered_by_insurance',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='insurance_policy_number',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='patient_paid_amount',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='status',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dispensed_by',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosage_instructions',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='prescriber',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity_dispensed',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity_prescribed',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('name', 'supplier')},
        ),
        migrations.RemoveField(
            model_name='supplierstockitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='supplierstockitem',
            name='supplier_item_code',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='height_cm',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='recorded_by',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='spo2_percentage',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='visit',
        ),
        migrations.RemoveField(
            model_name='vitals',
            name='weight_kg',
        ),
        migrations.AddField(
            model_name='adverseeventfollowingimmunization',
            name='event_description',
            field=models.TextField(default='', help_text='Detailed description of the adverse event.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allergy',
            name='diagnosed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='dosage_mg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dosage in milligrams', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medication',
            name='stock_item',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_details', to='api.stockitem'),
        ),
        migrations.AddField(
            model_name='medication',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='api.patient'),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='action',
            field=models.CharField(default='Unknown', help_text="e.g., 'Created', 'Updated Status', 'Added Item'", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='reason',
            field=models.TextField(default='', help_text="Reason for the patient's visit."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(default='', help_text="e.g., '1 tablet', '5ml'", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='duration_days',
            field=models.IntegerField(default=0, help_text='Duration in days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(default='', help_text="e.g., 'Twice daily', 'Every 4 hours'", max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='is_dispensed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prescription',
            name='patient_visit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='api.patientvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='prescribed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='location',
            field=models.CharField(blank=True, help_text='Physical location of the stock item in the facility.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum stock level before reordering is triggered.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='stockitem',
            name='unit',
            field=models.CharField(choices=[('Pill', 'Pill'), ('Tablet', 'Tablet'), ('Capsule', 'Capsule'), ('Syrup', 'Syrup'), ('Injection', 'Injection'), ('Vial', 'Vial'), ('Ampule', 'Ampule'), ('Bottle', 'Bottle'), ('Tube', 'Tube'), ('Pouch', 'Pouch'), ('Unit', 'Unit'), ('Other', 'Other')], default='Unit', max_length=50),
        ),
        migrations.AddField(
            model_name='supplierstockitem',
            name='last_supplied_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='supplierstockitem',
            name='supplied_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitals',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='vitals',
            name='patient_visit',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vitals', to='api.patientvisit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vitals',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='adversedrugreaction',
            name='medication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adverse_reactions_reported', to='api.medication'),
        ),
        migrations.AlterField(
            model_name='adversedrugreaction',
            name='reaction_description',
            field=models.TextField(help_text='Detailed description of the adverse reaction.'),
        ),
        migrations.AlterField(
            model_name='adversedrugreaction',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adrs_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adversedrugreaction',
            name='severity',
            field=models.CharField(blank=True, help_text='Severity of the reaction (e.g., Mild, Moderate, Severe, Life-threatening)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adverseeventfollowingimmunization',
            name='immunization_name',
            field=models.CharField(help_text='Name of the vaccine or immunization.', max_length=255),
        ),
        migrations.AlterField(
            model_name='adverseeventfollowingimmunization',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aefis_reported', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adverseeventfollowingimmunization',
            name='severity',
            field=models.CharField(blank=True, help_text='Severity of the event (e.g., Mild, Moderate, Severe, Life-threatening)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='allergen',
            field=models.CharField(help_text='Substance causing the allergy (e.g., Penicillin, Peanuts)', max_length=255),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='reaction',
            field=models.TextField(blank=True, help_text='Description of the allergic reaction (e.g., Rash, Anaphylaxis)', null=True),
        ),
        migrations.AlterField(
            model_name='allergy',
            name='severity',
            field=models.CharField(blank=True, help_text='Severity of the allergy (e.g., Mild, Moderate, Severe)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryhistory',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_history', to='api.stockitem'),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='condition',
            field=models.CharField(help_text='Name of the medical condition (e.g., Diabetes, Hypertension)', max_length=255),
        ),
        migrations.AlterField(
            model_name='medicalhistory',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the condition or treatment', null=True),
        ),
        migrations.AlterField(
            model_name='medication',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='change_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_history_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='stock_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='api.stockitem'),
        ),
        migrations.AlterField(
            model_name='pastprocedure',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes about the procedure and outcome', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_visits', to='api.facility'),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='visit_type',
            field=models.CharField(choices=[('Consultation', 'Consultation'), ('Follow-up', 'Follow-up'), ('Emergency', 'Emergency'), ('Check-up', 'Check-up'), ('Other', 'Other')], default='Consultation', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money'), ('Insurance', 'Insurance'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='api.medication'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Is the stock item currently in use or available?'),
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='api.supplier'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure_diastolic',
            field=models.IntegerField(blank=True, help_text='Diastolic Blood Pressure (mmHg)', null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='blood_pressure_systolic',
            field=models.IntegerField(blank=True, help_text='Systolic Blood Pressure (mmHg)', null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='heart_rate',
            field=models.IntegerField(blank=True, help_text='Heart Rate (bpm)', null=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vitals',
            name='respiratory_rate',
            field=models.IntegerField(blank=True, help_text='Respiratory Rate (breaths/min)', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='allergy',
            unique_together={('patient', 'allergen')},
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='location_in_facility',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='max_stock_level',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='min_stock_level',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='selling_price',
        ),
        migrations.RemoveField(
            model_name='stockitem',
            name='unit_of_measure',
        ),
    ]
